### ISSUE TITLE
device tracker does not get created after initial setup

### ISSUE THREAD

**Issue by Murder3D** [Danielhiversen/home_assistant_tractive#34]
Hi,

I have a tractive GPS tracker and I've installed the custom component using HACS.

I also modified my configuration.yaml adding the following code as per instructions:

```
# Tractive Device Tracker
device_tracker:
  - platform: tractive
    username: myemail@mail.com
    password: mypassword
```

The corresponding device tracker entity does not get created and therefore I am unable to track my dog from HA.

Username and password are correct, the tractive GPS tracker is on and it has both network and GPS signal (I can se the device in the tractive iOS app).

How can I solve this? Am I missing something?

Thank-you

Home Assistant 2021.7.3 running on rpi4 4GB
